config:
  target: http://localhost:3001
  phases:
    - duration: 60
      arrivalRate: 1000
scenarios:
  - flow:
      - get:
          url: "/products/25167/related"

# - duration: HOW MANY SECONDS TO TEST FOR
#   arrivalRate:  HOW MANY REQUESTS PER SECOND